- name: Install NGINX
  hosts: all
  tasks:
    - name: Install the latest version of NGINX
      ansible.builtin.apt:
        name: nginx
        state: present
      become: true

    - name: Start NGINX service
      ansible.builtin.service:
        name: nginx
        state: started
      become: true
