- name: Install Apache
  hosts: ansible-node
  tasks:
    - name: Install the latest version of Apache
      ansible.builtin.yum:
        name: httpd
        state: latest
      become: true

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started
      become: true
